<template>
  <div class="design-panel">
    <div v-if="error" class="p-notification--negative">
      <div class="p-notification__content">
        <p class="p-notification__message">{{ error }}</p>
      </div>
    </div>

    <template v-if="deployment.design_doc">
      <div class="design-panel__body">
        <div class="design-panel__main">
          <header v-if="!editing" class="design-panel__doc-header" data-testid="design-doc-header">
            <h3 class="design-panel__doc-title">{{ designDocTitle }}</h3>
            <p class="design-panel__doc-meta">{{ docMeta }}</p>
          </header>
          <textarea
            v-if="editing"
            v-model="editContent"
            class="design-panel__editor"
            data-testid="design-editor"
          />
          <div
            v-else
            class="design-panel__preview doc-body"
            data-testid="design-preview"
            v-html="renderedDesign"
          />

          <div v-if="editing" class="design-panel__edit-bar" data-testid="design-edit-bar">
            <button class="p-button--base is-dense" type="button" data-testid="cancel-edit-btn" @click="cancelEdit">Cancel</button>
            <button class="p-button--positive is-dense" type="button" data-testid="save-design-btn" :disabled="saving" @click="saveEdit">
              {{ saving ? 'Saving…' : 'Save' }}
            </button>
          </div>
        </div>

        <aside v-if="!editing" class="design-panel__sidebar">
          <div class="design-panel__sidebar-actions">
            <button
              class="p-button--base is-dense"
              data-testid="edit-design-btn"
              type="button"
              :disabled="proposing"
              @click="startEdit"
            >Edit</button>
            <BusyStatus v-if="busyLabel" :text="busyLabel" />
          </div>
          <div class="design-panel__prompt">
            <label for="design-prompt">Propose a change</label>
            <textarea
              id="design-prompt"
              v-model="promptText"
              rows="5"
              data-testid="design-prompt"
              placeholder="Describe what you'd like to change"
            />
            <button
              class="p-button--base is-dense"
              type="button"
              data-testid="propose-design-btn"
              :disabled="!promptText.trim() || proposing"
              @click="propose"
            >{{ proposing ? 'Proposing…' : 'Propose' }}</button>
          </div>
        </aside>
      </div>
    </template>
  </div>
</template>

<script setup>
import { ref, computed, watch } from 'vue';
import { renderMarkdown } from '../../lib/markdown.js';
import { getArtifact, updateArtifact, proposeArtifactChange } from '../../lib/api.js';
import BusyStatus from './BusyStatus.vue';

const props = defineProps({
  projectId:  { type: String, required: true },
  deployment: { type: Object, required: true },
});
const emit = defineEmits(['refresh']);

const designContent = ref('');
const editing         = ref(false);
const editContent    = ref('');
const saving          = ref(false);
const proposing      = ref(false);
const promptText    = ref('');
const error          = ref(null);

const renderedDesign = computed(() => designContent.value ? renderMarkdown(designContent.value, {}, {}) : '');

const designDocTitle = computed(() => props.deployment.design_doc?.title ?? 'Design');

const docMeta = computed(() => {
  const parts = [];
  const by = props.deployment.created_by;
  if (by) parts.push(by === 'assistant' ? 'Generated by the assistant' : `Created by ${by}`);
  const at = props.deployment.created_at;
  if (at) parts.push(formatDate(at));
  return parts.join(' · ');
});

const busyLabel = computed(() => {
  if (saving.value)   return 'Saving design…';
  if (proposing.value) return 'Proposing a change…';
  return null;
});

function formatDate(iso) {
  return new Date(iso).toLocaleDateString(undefined, { year: 'numeric', month: 'short', day: 'numeric' });
}

async function loadDesignContent() {
  if (!props.deployment.design_doc) {
    designContent.value = '';
    return;
  }
  try {
    const artifact = await getArtifact(props.deployment.design_doc.id);
    designContent.value = artifact.content || '';
  } catch {
    designContent.value = '';
  }
}

function startEdit() {
  if (editing.value) {
    editing.value = false;
    return;
  }
  editContent.value = designContent.value;
  editing.value = true;
}

function cancelEdit() {
  editing.value = false;
  editContent.value = '';
}

async function saveEdit() {
  saving.value = true;
  error.value = null;
  try {
    await updateArtifact(props.deployment.design_doc.id, {
      title: props.deployment.design_doc.title ?? 'Design',
      kind: 'markdown',
      content: editContent.value,
    });
    designContent.value = editContent.value;
    editing.value = false;
    emit('refresh');
  } catch (e) {
    error.value = e.message || 'Failed to save';
  } finally {
    saving.value = false;
  }
}

async function propose() {
  if (!promptText.value.trim()) return;
  proposing.value = true;
  error.value = null;
  try {
    await proposeArtifactChange(props.projectId, props.deployment.id, {
      artifact_id: props.deployment.design_doc.id,
      source: 'prompt',
      explanation: promptText.value.trim(),
      current_content: designContent.value,
      proposed_content: promptText.value.trim(),
    });
    promptText.value = '';
  } catch (e) {
    error.value = e.message || 'Failed to propose change';
  } finally {
    proposing.value = false;
  }
}

watch(() => props.deployment.design_doc?.id, loadDesignContent, { immediate: true });
</script>