import { describe, it, expect, vi, beforeEach } from 'vitest';
import { mount, flushPromises } from '@vue/test-utils';

vi.mock('monaco-editor', () => {
  let changeCb = null;
  const mockEditor = {
    getValue: vi.fn(() => ''),
    setValue: vi.fn(),
    onDidChangeModelContent: vi.fn((cb) => { changeCb = cb; }),
    dispose: vi.fn(),
    updateOptions: vi.fn(),
  };
  const mockDiffEditor = {
    setModel: vi.fn(),
    getModel: vi.fn(() => null),
    getModifiedEditor: vi.fn(() => mockEditor),
    dispose: vi.fn(),
  };
  const editorApi = {
    create: vi.fn(() => mockEditor),
    createDiffEditor: vi.fn(() => mockDiffEditor),
    createModel: vi.fn(() => ({ dispose: vi.fn() })),
  };
  return {
    default: { editor: editorApi },
    editor: editorApi,
    __mockEditor: mockEditor,
    __mockDiffEditor: mockDiffEditor,
    __getChangeCb: () => changeCb,
    __resetChangeCb: () => { changeCb = null; },
  };
});

vi.mock('../../src/lib/api.js', async (importOriginal) => {
  const actual = await importOriginal();
  return {
    ...actual,
    getArtifact:           vi.fn(),
    generateDesignDecisions: vi.fn(),
    reviseDesign:          vi.fn(),
    updateDesignContent:   vi.fn(),
    proposeArtifactChange: vi.fn(),
  };
});

vi.mock('../../src/lib/markdown.js', () => ({
  renderMarkdown: vi.fn(() => '<p>rendered</p>'),
}));

import DesignPanel from '../../src/components/deployment/DesignPanel.vue';
import * as api from '../../src/lib/api.js';
import * as monaco from 'monaco-editor';
import { useProjectStore } from '../../src/stores/project.js';

const DEPLOYMENT_WITH_DESIGN = {
  id: 'd1', name: 'Rollout',
  design_doc: { id: 'a1', title: 'Design', created_by: 'assistant', created_at: '2026-08-26T10:00:00Z' },
};

function mountPanel(deployment = DEPLOYMENT_WITH_DESIGN) {
  return mount(DesignPanel, {
    props: { projectId: 'proj-1', deployment },
  });
}

function getMockEditor() {
  return monaco.__mockEditor;
}

function mockPdfResponse({ status = 200, pdfStatus = 'ready' } = {}) {
  if (status === 503) {
    return { ok: false, status: 503, headers: { get: () => null } };
  }
  return {
    ok: true,
    status: 200,
    headers: { get: (name) => (name === 'x-design-pdf-status' ? pdfStatus : null) },
    blob: () => Promise.resolve(new Blob(['%PDF'], { type: 'application/pdf' })),
  };
}

describe('DesignPanel', () => {
  beforeEach(() => {
    vi.clearAllMocks();
    monaco.__resetChangeCb();
    const e = getMockEditor();
    e.getValue.mockReturnValue('');
    api.getArtifact.mockResolvedValue({ content: '# My Design' });
    api.updateDesignContent.mockResolvedValue({});
    api.proposeArtifactChange.mockResolvedValue({ id: 'p1', status: 'pending' });
    global.fetch = vi.fn(() => Promise.resolve(mockPdfResponse()));
    global.URL.createObjectURL = vi.fn(() => 'blob:mock-url');
    global.URL.revokeObjectURL = vi.fn();
  });

  it('shows a document header with the design title and metadata when design doc exists', async () => {
    const w = mountPanel();
    await flushPromises();
    const header = w.find('[data-testid="design-doc-header"]');
    expect(header.exists()).toBe(true);
    expect(header.text()).toContain('Design');
  });

  it('titles the document "Design document" alone when there is no template or project name', async () => {
    const w = mountPanel();
    await flushPromises();
    expect(w.get('[data-testid="design-doc-header"] h3').text()).toBe('Design document');
  });

  it('titles the document as "Design document - <product>-<project>" when both are known', async () => {
    useProjectStore().selectedProject = { id: 'proj-1', name: 'Acme Rollout' };
    const deployment = {
      ...DEPLOYMENT_WITH_DESIGN,
      template: { id: 't1', name: 'Edge Gateway' },
    };
    const w = mountPanel(deployment);
    await flushPromises();
    expect(w.get('[data-testid="design-doc-header"] h3').text()).toBe('Design document - Edge Gateway-Acme Rollout');
  });

  it('does not show a product template capsule in the header', async () => {
    useProjectStore().selectedProject = { id: 'proj-1', name: 'Acme Rollout' };
    const deployment = {
      ...DEPLOYMENT_WITH_DESIGN,
      template: { id: 't1', name: 'Edge Gateway' },
    };
    const w = mountPanel(deployment);
    await flushPromises();
    expect(w.find('[data-testid="design-template-chip"]').exists()).toBe(false);
  });

  it('shows only the last modification date, with no author label', async () => {
    const w = mountPanel();
    await flushPromises();
    const text = w.find('[data-testid="design-doc-header"]').text();
    expect(text).toContain('Last modified');
    expect(text).not.toContain('Generated by');
    expect(text).not.toContain('Created by');
  });

  it('prefers the design doc updated_at over created_at for the modification date', async () => {
    const deployment = {
      ...DEPLOYMENT_WITH_DESIGN,
      design_doc: { id: 'a1', title: 'Design', created_by: 'assistant', created_at: '2026-08-01T10:00:00Z', updated_at: '2026-08-26T10:00:00Z' },
    };
    const w = mountPanel(deployment);
    await flushPromises();
    const text = w.find('[data-testid="design-doc-header"]').text();
    expect(text).toContain('Aug 26, 2026');
    expect(text).not.toContain('Aug 1, 2026');
  });

  it('renders the design preview with the doc-body class for markdown styling', async () => {
    const w = mountPanel();
    await flushPromises();
    const preview = w.find('[data-testid="design-preview"]');
    expect(preview.exists()).toBe(true);
    expect(preview.classes()).toContain('doc-body');
  });

  it('shows the edit and download buttons when design doc exists', async () => {
    const w = mountPanel();
    await flushPromises();
    expect(w.find('[data-testid="edit-design-btn"]').exists()).toBe(true);
    const dl = w.find('[data-testid="download-design-btn"]');
    expect(dl.exists()).toBe(true);
    expect(dl.attributes('href')).toBe('/artifacts/a1/download');
  });

  it('edit toggles the monaco editor with current content', async () => {
    api.getArtifact.mockResolvedValue({ content: '# My Design' });
    const w = mountPanel();
    await flushPromises();
    expect(w.find('[data-testid="design-editor"]').exists()).toBe(false);
    await w.find('[data-testid="edit-design-btn"]').trigger('click');
    await flushPromises();
    const editor = w.find('[data-testid="design-editor"]');
    expect(editor.exists()).toBe(true);
    expect(monaco.editor.create).toHaveBeenCalled();
    expect(getMockEditor().getValue()).toBe('');
  });

  it('hides the propose prompt while editing and shows a sticky edit bar', async () => {
    const w = mountPanel();
    await flushPromises();
    expect(w.find('[data-testid="design-prompt"]').exists()).toBe(false);
    await w.find('[data-testid="propose-toggle-btn"]').trigger('click');
    expect(w.find('[data-testid="design-prompt"]').exists()).toBe(true);
    await w.find('[data-testid="edit-design-btn"]').trigger('click');
    await flushPromises();
    expect(w.find('[data-testid="design-prompt"]').exists()).toBe(false);
    expect(w.find('[data-testid="design-edit-bar"]').exists()).toBe(true);
  });

  it('save edit calls updateDesignContent with new content and emits refresh', async () => {
    api.getArtifact.mockResolvedValue({ content: '# Old' });
    const e = getMockEditor();
    e.getValue.mockReturnValue('# New content');
    const w = mountPanel();
    await flushPromises();
    await w.find('[data-testid="edit-design-btn"]').trigger('click');
    await flushPromises();
    await w.find('[data-testid="save-design-btn"]').trigger('click');
    await flushPromises();
    expect(api.updateDesignContent).toHaveBeenCalledWith('proj-1', 'd1', expect.objectContaining({
      title: 'Design', content: '# New content',
    }));
    expect(w.emitted('refresh')).toBeTruthy();
  });

  it('prompt box produces a proposal via proposeArtifactChange', async () => {
    api.getArtifact.mockResolvedValue({ content: '# Old' });
    const w = mountPanel();
    await flushPromises();
    await w.find('[data-testid="propose-toggle-btn"]').trigger('click');
    await w.find('[data-testid="design-prompt"]').setValue('Add a load balancer section');
    await w.find('[data-testid="propose-design-btn"]').trigger('click');
    await flushPromises();
    expect(api.proposeArtifactChange).toHaveBeenCalledWith('proj-1', 'd1', expect.objectContaining({
      artifact_id: 'a1',
    }));
  });

  it('prompt box disabled when empty', async () => {
    const w = mountPanel();
    await flushPromises();
    await w.find('[data-testid="propose-toggle-btn"]').trigger('click');
    const btn = w.find('[data-testid="propose-design-btn"]');
    expect(btn.attributes('disabled')).toBeDefined();
  });

  describe('proposing a change reuses the initial generation UI', () => {
    async function openProposeAndSubmit(w, text = 'Add a load balancer section') {
      await w.find('[data-testid="propose-toggle-btn"]').trigger('click');
      await w.find('[data-testid="design-prompt"]').setValue(text);
      await w.find('[data-testid="propose-design-btn"]').trigger('click');
      await flushPromises();
    }

    it('shows the same DesignGenerationPanel used for the initial generation while the proposal streams', async () => {
      const w = mountPanel();
      await flushPromises();
      await openProposeAndSubmit(w);
      const gen = w.findComponent({ name: 'DesignGenerationPanel' });
      expect(gen.exists()).toBe(true);
      expect(gen.props('streamFn')).toBe(api.proposeDesignChangeStream);
      expect(gen.props('body')).toEqual({ explanation: 'Add a load balancer section', artifact_ids: [] });
      expect(gen.props('deploymentId')).toBe('d1');
      expect(w.find('[data-testid="design-prompt-panel"]').exists()).toBe(false);
    });

    it('hides the header actions while a proposal is generating', async () => {
      const w = mountPanel();
      await flushPromises();
      await openProposeAndSubmit(w);
      expect(w.find('[data-testid="edit-design-btn"]').exists()).toBe(false);
      expect(w.find('[data-testid="propose-toggle-btn"]').exists()).toBe(false);
    });

    it('mounts the diff editor for review once the generation panel reports the proposal is done', async () => {
      const w = mountPanel();
      await flushPromises();
      await openProposeAndSubmit(w);
      const gen = w.findComponent({ name: 'DesignGenerationPanel' });
      gen.vm.$emit('done', { answer: '# Revised design' });
      await flushPromises();
      expect(w.find('[data-testid="design-proposal-diff"]').exists()).toBe(true);
      expect(w.findComponent({ name: 'DesignGenerationPanel' }).exists()).toBe(false);
      expect(monaco.editor.createDiffEditor).toHaveBeenCalled();
    });

    it('returns to the document view without an error when the generation panel emits cancel', async () => {
      const w = mountPanel();
      await flushPromises();
      await openProposeAndSubmit(w);
      const gen = w.findComponent({ name: 'DesignGenerationPanel' });
      gen.vm.$emit('cancel');
      await flushPromises();
      expect(w.findComponent({ name: 'DesignGenerationPanel' }).exists()).toBe(false);
      expect(w.find('[data-testid="edit-design-btn"]').exists()).toBe(true);
      expect(w.find('.p-notification--negative').exists()).toBe(false);
    });

    it('shows an error and returns to the document view if the proposal finishes with no content', async () => {
      const w = mountPanel();
      await flushPromises();
      await openProposeAndSubmit(w);
      const gen = w.findComponent({ name: 'DesignGenerationPanel' });
      gen.vm.$emit('done', { answer: '   ' });
      await flushPromises();
      expect(w.findComponent({ name: 'DesignGenerationPanel' }).exists()).toBe(false);
      expect(w.find('.p-notification--negative').text()).toContain('Failed to propose change');
    });
  });

  it('cancel edit closes the editor without saving', async () => {
    const w = mountPanel();
    await flushPromises();
    await w.find('[data-testid="edit-design-btn"]').trigger('click');
    await flushPromises();
    await w.find('[data-testid="cancel-edit-btn"]').trigger('click');
    expect(w.find('[data-testid="design-editor"]').exists()).toBe(false);
  });

  it('shows the cached pdf preview and enables the download button once ready', async () => {
    const w = mountPanel();
    await flushPromises();
    expect(w.find('[data-testid="design-preview"]').exists()).toBe(true);
    expect(w.find('[data-testid="design-preview"]').attributes('src')).toBe('blob:mock-url');
    expect(w.find('[data-testid="download-design-pdf-btn"]').exists()).toBe(true);
  });

  it('shows a preparing state while the pdf is still being generated, with no download button', async () => {
    global.fetch = vi.fn(() => Promise.resolve(mockPdfResponse({ status: 503 })));
    const w = mountPanel();
    await flushPromises();
    expect(w.find('[data-testid="design-pdf-pending"]').exists()).toBe(true);
    expect(w.find('[data-testid="design-preview"]').exists()).toBe(false);
    expect(w.find('[data-testid="download-design-pdf-btn"]').exists()).toBe(false);
    w.unmount();
  });

  it('shows an updating note alongside the stale preview while a newer version regenerates', async () => {
    global.fetch = vi.fn(() => Promise.resolve(mockPdfResponse({ pdfStatus: 'stale' })));
    const w = mountPanel();
    await flushPromises();
    expect(w.find('[data-testid="design-pdf-stale-note"]').exists()).toBe(true);
    expect(w.find('[data-testid="design-preview"]').exists()).toBe(true);
    w.unmount();
  });

  it('shows an error state when the pdf preview fails to load', async () => {
    global.fetch = vi.fn(() => Promise.resolve({ ok: false, status: 500, headers: { get: () => null } }));
    const w = mountPanel();
    await flushPromises();
    expect(w.find('[data-testid="design-pdf-error"]').exists()).toBe(true);
    expect(w.find('[data-testid="design-preview"]').exists()).toBe(false);
  });

  it('reloads the pdf preview after a successful save', async () => {
    const e = getMockEditor();
    e.getValue.mockReturnValue('# New content');
    const w = mountPanel();
    await flushPromises();
    global.fetch.mockClear();
    await w.find('[data-testid="edit-design-btn"]').trigger('click');
    await flushPromises();
    await w.find('[data-testid="save-design-btn"]').trigger('click');
    await flushPromises();
    expect(global.fetch).toHaveBeenCalled();
  });
});
